### PR TITLE
Changelog update

### PR DESCRIPTION
**Pull request by Qiao-Jin**
This PR addes change log from neo3 preview 2 to preview 3

### CODE REVIEW

**Comment by erikzhang** [comment]
Why delete the old logs?

**Comment by superboyiii** [comment]
> Why delete the old logs?

Because they should be in master-2.x branch or you think they should be a log of neo3?

**Comment by erikzhang** [comment]
Please create a new file. Don't delete the old one.

**Comment by superboyiii** [comment]
@erikzhang Please review again.

**Pull request merged**
