### PR TITLE
Improve progress bar aspect

### PR DESCRIPTION
**Pull request by shargon**
This patch improve the progress bar aspect and experience

image

### CODE REVIEW

**Comment by erikzhang** [comment]
Does it work in neo-gui console window?

**Comment by shargon** [comment]
I will test it

**Comment by shargon** [comment]
image

Now it's compatible

**Comment by superboyiii** [comment]
Wow, looks great. Let me have a test now.

**Comment by superboyiii** [comment]
@shargon Good work Shargon. Looks so nice for progress display. It works well.
image
image
image
image 
I just made a little adjustment since I think block info is really important to display especially when making bootstrap package.
image

**Comment by shargon** [comment]
Thanks you @superboyiii for your review! Did you tested `neo-gui` console?

**Comment by superboyiii** [comment]
> Thanks you @superboyiii for your review! Did you tested `neo-gui` console?

I tried it on neo-gui just now, find an issue: When  making exprt blocks or import key, if the number of WIF is a little big (100 lines), a conflict will exist in `Application.ThreadContext.RunMessageLoop` which makes illegal value.
image
image
image

**Comment by shargon** [comment]
Could you create a issue for this? I think that it's not related tu this PR

**Comment by wanglongfei88** [comment]
> Could you create a issue for this? I think that it's not related tu this PR

Is it necessary to test and fix it on current GUI repo since we are designing and developing a new Neo-GUI?

**Comment by shargon** [comment]
> Is it necessary to test and fix it on current GUI repo since we are designing and developing a new Neo-GUI?

According to your comment it seems yes https://github.com/neo-project/neo-node/issues/515#issuecomment-565973656 , I think that we should check that at least, it's working as before the change, not worst :P what do you think?

**Comment by wanglongfei88** [comment]
I meant to keep the GUI code before we finished the new one.  

But maybe we should not spend too much time fixing this old GUI. Because we did not update GUI code according to Neo3 codes changes. So it is going to be a lot of bugs and issues if testing team test this old GUI repo.

**Comment by shargon** [comment]
Agree

**Comment by superboyiii** [comment]
@shargon @erikzhang Shall I open an issue for this or just make full test after @wanglongfei88 finishing the restructure of neo-gui? But I think this PR has no problem.

**Comment by erikzhang** [comment]
New issue please.

**Comment by superboyiii** [comment]
> New issue please.

Fine.

**Pull request merged**
