### PR TITLE
Fix plugin commands

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-node/issues/556

### CODE REVIEW

**Comment by nicolegys** [comment]
key.ToLower cannot get the value
image

**Comment by shargon** [comment]
@nicolegys please take a look again

**Comment by nicolegys** [comment]
Thank you @shargon . Now it works well.
Do we need to display all the command help information including the plugins when we call `help`?
Now it looks like this (`StatesDumper` and `PerformanceMonitor` are installed):
a bit messy
Or maybe we need to put all the plugin comands in Category `Plugin Commands`?
image

**Comment by shargon** [comment]
Both options are good to me, what do you prefer? it's enough with change the category of the plugin command.

**Comment by nicolegys** [comment]
I prefer to have plugin commands in the `Plugin Commands` catagory, to make the help information more clearly. And whether the plugins are installed or not, they will not affect the categories of neo-cli itself.
```
Base Commands:
...
Blockchain Commands:
...
Consensus Commands:
...
Contract Commands:
...
Network Commands:
...
Node Commands:
...
Plugin Commands:
...
Wallet Commands:
...
```

But maybe the plugin commands need to have their own catagories，like this 
```
neo> help PerformanceMonitor
Block Commands:
        block avgtime [blockCount=1000]
        block sync
        block time <blockIndexOrHash>
        block timesincelast
Check Commands:
        check cpu
        check memory
        check threads
Consensus Commands:
        commit time
        confirmation time
        payload time
Network Commands:
        connected
        ping [ipaddress=null]
        rpc time <url>
Transaction Commands:
        tx avgsize [txCount=1000]
        tx size <transactionHash>
```
I'm not sure if changing all of their categories to `Plugin Commands` will make the help information more friendly. Or maybe we need subcategories? What do you think?

**Pull request merged**
