### PR TITLE
Show `ScriptHash` in `list address`

### LINKED ISSUE #565: Show ScriptHash in neo-cli
We need use `ScriptHash` in neo-cli commands, like `UInt160[] witnessAddress`, so i think it's better to show `ScriptHash` in `list address` command.

### PR DESCRIPTION
**Pull request by ProDog**
Close #565

### CODE REVIEW

**Comment by erikzhang** [comment]
Maybe it should still be one entry per line.

**Comment by shargon** [comment]
Could you use a different PR for vote?

**Comment by ProDog** [comment]
> Could you use a different PR for vote?

OK, forgot to switch branches.

**Comment by ProDog** [comment]
:rofl:

**Comment by shargon** [comment]
Test fail

**Comment by ProDog** [comment]
> Test fail

I can't find the problem, please help me @shargon .

**Pull request merged**
