### PR TITLE
[master-2.x] Add minimum network fee

### PR DESCRIPTION
**Pull request by Qiao-Jin**
This PR adds a adjustable MinimumNetworkFee into protocol setting.
Related to [neo-core #1901](https://github.com/neo-project/neo/pull/1901)

### CODE REVIEW

**Comment by erikzhang** [comment]
If the consensus nodes change the policy of `MinimumNetworkFee`, how do other nodes know it?

**Comment by Qiao-Jin** [comment]
> If the consensus nodes change the policy of `MinimumNetworkFee`, how do other nodes know it?

Each time upon changing a public announce can be published
A `MinimumNetworkFee ` RPC call can also be used to know the `MinimumNetworkFee` of seed nodes.

**Comment by erikzhang** [comment]
But the seed nodes are different from the consensus nodes.

**Comment by Qiao-Jin** [comment]
> But the seed nodes are different from the consensus nodes.

That's true, but consensus node cannot expose network ID so they cannot broadcast in public by themselves... unless they publish some posts onchain in terms of transactions, but that's another story.

**Review by erikzhang — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Review by vncoelho — APPROVED** [review]

**Pull request merged**
