### PR TITLE
add unvote function

### PR DESCRIPTION
**Pull request by cloud8little**

### CODE REVIEW

**Review by erikzhang — APPROVED** [review]

**Comment by erikzhang** [comment]
Test?

**Comment by shargon** [comment]
Is not better to allow null on `publicKey` and use `vote`?

**Comment by cloud8little** [comment]
> Is not better to allow null on `publicKey` and use `vote`?

If you mean set the publicKey as null by default when user did not input the publicKey, it is feasible, but I think it is not straightforward to express the meaning of unvote. User may forget to input the publickey field and actually it will cancel the user's vote, it is very confused.

**Review by nicolegys — APPROVED** [review]
tested

**Review by shargon — APPROVED** [review]

**Pull request merged**
